spring.application.name=eComm

# =======================================================================
# 1. DATABASE CONFIGURATION (MySQL)
# =======================================================================

# --- OLD AWS RDS SETUP (Commented Out) ---
# spring.datasource.url=${DATABASE_URL}
# spring.datasource.username=${DATABASE_ADMIN_USERNAME}
# spring.datasource.password=${DATABASE_PASSWORD}

# --- NEW ALWAYS FREE SETUP (Aiven Cloud MySQL) ---
# Get these details instantly by creating a free account at https://aiven.io
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_ADMIN_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

## JPA PROPERTI Help us to generate table
spring.jpa.hibernate.ddl-auto=update 
server.servlet.context-path=/api/v1.0
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =======================================================================
# 2. OBJECT STORAGE SETUP (S3 Compatible)
# =======================================================================

# --- OLD AWS S3 SETUP (Commented Out) ---
# aws.access.key=${AWS_ACCESS_KEY}
# aws.secret.key=8pVEoxa/7iwuWZdoXSJDMKHWjZ+iqf1AAqAcevEH
# aws.region= ap-southeast-2
# aws.bucket.name=billing-software-vandeshaws

# =======================================================================
# 2. Supabase S3 Bucket
# =======================================================================

aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=ap-northeast-1
aws.bucket.name=posbilling_obj
aws.endpoint=https://vtxyegvfbrbdfopmrqiy.storage.supabase.co/storage/v1/s3

## jwt
jwt.secret.key= ${JWT_SECRET_KEY}

## Razorpay
razorpay.key-id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_SECREAT_KEY}

# shows you in logs when transactions start/commit/rollback
logging.level.org.springframework.transaction=DEBUG

# shows actual SQL being executed
logging.level.org.hibernate.SQL=DEBUG

# 1. Optimize database connections to save memory overhead
spring.datasource.hikari.maximum-pool-size=2

# 2. Limit active Tomcat threads to reduce memory allocated to thread stacks
server.tomcat.threads.max=20

# Variable Name / Key: {JAVA_TOOL_OPTIONS}  Value: {-Xms200m -Xmx250m -XX:+UseSerialGC}